# Generated by Django 5.1.1 on 2024-09-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('vid_file', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
        ),
    ]
